a

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -1,167 +1,167 @@
-name: CD to EKS
+# name: CD to EKS
 
-on:
-  workflow_run:
-    workflows: ["CI Build & Test"]
-    types:
-      - completed
-  workflow_dispatch:
-    inputs:
-      action:
-        description: "Apply or Destroy"
-        required: true
-        default: "apply"
-        type: choice
-        options:
-          - apply
-          - destroy
+# on:
+#   workflow_run:
+#     workflows: ["CI Build & Test"]
+#     types:
+#       - completed
+#   workflow_dispatch:
+#     inputs:
+#       action:
+#         description: "Apply or Destroy"
+#         required: true
+#         default: "apply"
+#         type: choice
+#         options:
+#           - apply
+#           - destroy
 
-permissions:
-  id-token: write
-  contents: read
+# permissions:
+#   id-token: write
+#   contents: read
 
-env:
-  AWS_REGION: us-west-2
-  CLUSTER_NAME: eksdemo-cluster
-  VPC_NAME: eksdemo-vpc
-  ARGOCD_CLB: eksdemo-argocd-clb
-  FLASK_ALB: eksdemo-flask-alb
+# env:
+#   AWS_REGION: us-west-2
+#   CLUSTER_NAME: eksdemo-cluster
+#   VPC_NAME: eksdemo-vpc
+#   ARGOCD_CLB: eksdemo-argocd-clb
+#   FLASK_ALB: eksdemo-flask-alb
 
-jobs:
-  deploy:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+# jobs:
+#   deploy:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v4
 
-      - name: Configure AWS
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
-          aws-region: ${{ env.AWS_REGION }}
-          role-session-name: github-actions
+#       - name: Configure AWS
+#         uses: aws-actions/configure-aws-credentials@v4
+#         with:
+#           role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+#           aws-region: ${{ env.AWS_REGION }}
+#           role-session-name: github-actions
 
-      # Update kubeconfig
-      - name: Update kubeconfig for EKS
-        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
-        run: |
-          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}
+#       # Update kubeconfig
+#       - name: Update kubeconfig for EKS
+#         if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
+#         run: |
+#           aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}
 
-      # Configure aws-auth
-      - name: Configure aws-auth
-        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
-        run: |
-          cat <<EOF | kubectl apply -f -
-          apiVersion: v1
-          kind: ConfigMap
-          metadata:
-            name: aws-auth
-            namespace: kube-system
-          data:
-            mapUsers: |
-              - userarn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:user/${{ secrets.AWS_USER }}
-                username: ${{ secrets.AWS_USER }}
-                groups:
-                  - system:masters
-          EOF
+#       # Configure aws-auth
+#       - name: Configure aws-auth
+#         if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
+#         run: |
+#           cat <<EOF | kubectl apply -f -
+#           apiVersion: v1
+#           kind: ConfigMap
+#           metadata:
+#             name: aws-auth
+#             namespace: kube-system
+#           data:
+#             mapUsers: |
+#               - userarn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:user/${{ secrets.AWS_USER }}
+#                 username: ${{ secrets.AWS_USER }}
+#                 groups:
+#                   - system:masters
+#           EOF
 
-      # Install ArgoCD
-      - name: Install ArgoCD
-        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
-        run: |
-          helm repo add argo https://argoproj.github.io/argo-helm
-          helm repo update
-          helm upgrade --install argocd argo/argo-cd \
-            --namespace argocd \
-            --create-namespace \
-            --set server.service.type=LoadBalancer \
-            --set-string server.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"=classic \
-            --set server.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-name"="${{ env.ARGOCD_CLB }}"
-          kubectl -n argocd rollout status deployment/argocd-server --timeout=5m
+#       # Install ArgoCD
+#       - name: Install ArgoCD
+#         if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
+#         run: |
+#           helm repo add argo https://argoproj.github.io/argo-helm
+#           helm repo update
+#           helm upgrade --install argocd argo/argo-cd \
+#             --namespace argocd \
+#             --create-namespace \
+#             --set server.service.type=LoadBalancer \
+#             --set-string server.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"=classic \
+#             --set server.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-name"="${{ env.ARGOCD_CLB }}"
+#           kubectl -n argocd rollout status deployment/argocd-server --timeout=5m
 
-      # Deploy apps
-      - name: Get VPC and Deploy Apps
-        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
-        run: |
-          export VPC_ID=$(aws ec2 describe-vpcs \
-            --filters "Name=tag:Name,Values=${{ env.VPC_NAME }}" \
-            --query "Vpcs[0].VpcId" --output text)
-          export ECR_NAME=${{ secrets.ECR_NAME }}
-          export AWS_ACCOUNT_NUMBER=${{ secrets.AWS_ACCOUNT_NUMBER }}
-          envsubst < ArgoCD/externalCharts/infra.yaml | kubectl apply -f -
-          envsubst < ArgoCD/myChart/argo.yaml | kubectl apply -f -
-          sleep 10
-          kubectl get applications -n argocd
+#       # Deploy apps
+#       - name: Get VPC and Deploy Apps
+#         if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
+#         run: |
+#           export VPC_ID=$(aws ec2 describe-vpcs \
+#             --filters "Name=tag:Name,Values=${{ env.VPC_NAME }}" \
+#             --query "Vpcs[0].VpcId" --output text)
+#           export ECR_NAME=${{ secrets.ECR_NAME }}
+#           export AWS_ACCOUNT_NUMBER=${{ secrets.AWS_ACCOUNT_NUMBER }}
+#           envsubst < ArgoCD/externalCharts/infra.yaml | kubectl apply -f -
+#           envsubst < ArgoCD/myChart/argo.yaml | kubectl apply -f -
+#           sleep 10
+#           kubectl get applications -n argocd
 
-      # Smoke test
-      - name: Smoke Test
-        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
-        run: |
-          for i in {1..100}; do
-            http_status=$(curl -s -o /dev/null -w "%{http_code}" https://www.saharbittman.com || echo "000")
+#       # Smoke test
+#       - name: Smoke Test
+#         if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
+#         run: |
+#           for i in {1..100}; do
+#             http_status=$(curl -s -o /dev/null -w "%{http_code}" https://www.saharbittman.com || echo "000")
 
-            if [ "$http_status" = "200" ]; then
-              echo "✅ App is live! ($http_status)"
-              exit 0
-            fi
+#             if [ "$http_status" = "200" ]; then
+#               echo "✅ App is live! ($http_status)"
+#               exit 0
+#             fi
 
-            echo "⏳ Attempt $i/100 - Status: $http_status"
-            sleep 15
-          done
+#             echo "⏳ Attempt $i/100 - Status: $http_status"
+#             sleep 15
+#           done
 
-          echo "❌ Smoke test failed"
-          exit 1
-
-
-       # ========== DESTROY ==========
-      - name: Destroy Everything
-        if: github.event.inputs.action == 'destroy' || failure()
-        run: |
-          echo "🗑️ Starting cleanup..."
-          aws eks update-kubeconfig --region "${{ env.AWS_REGION }}" --name "${{ env.CLUSTER_NAME }}" || true
-          echo "🔧 Removing Kubernetes finalizers..."
-          kubectl get applicationset.argoproj.io -n argocd -o name 2>/dev/null | \
-            xargs -r -I {} kubectl patch {} -n argocd -p '{"metadata":{"finalizers":[]}}' --type=merge || true
-          kubectl get applications.argoproj.io -n argocd -o name 2>/dev/null | \
-            xargs -r -I {} kubectl patch {} -n argocd -p '{"metadata":{"finalizers":[]}}' --type=merge || true
-          kubectl get ingress -A -o name 2>/dev/null | \
-            xargs -r -I {} kubectl patch {} -p '{"metadata":{"finalizers":[]}}' --type=merge || true
-          echo "🗑️ Deleting ingresses..."
-          kubectl delete ingress --all -A --timeout=60s || true
-          echo "🗑️ Deleting ArgoCD ApplicationSets..."
-          kubectl delete applicationset.argoproj.io --all -n argocd --timeout=60s || true
-          echo "🗑️ Deleting ArgoCD Applications..."
-          kubectl delete applications.argoproj.io --all -n argocd --timeout=60s || true
-          echo "🗑️ Uninstalling ArgoCD..."
-          helm uninstall argocd -n argocd --timeout=2m || true
+#           echo "❌ Smoke test failed"
+#           exit 1
 
 
-  destroy-bootstrap:
-    needs: deploy
-    if: github.event.inputs.action == 'destroy' && success()
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+#        # ========== DESTROY ==========
+#       - name: Destroy Everything
+#         if: github.event.inputs.action == 'destroy' || failure()
+#         run: |
+#           echo "🗑️ Starting cleanup..."
+#           aws eks update-kubeconfig --region "${{ env.AWS_REGION }}" --name "${{ env.CLUSTER_NAME }}" || true
+#           echo "🔧 Removing Kubernetes finalizers..."
+#           kubectl get applicationset.argoproj.io -n argocd -o name 2>/dev/null | \
+#             xargs -r -I {} kubectl patch {} -n argocd -p '{"metadata":{"finalizers":[]}}' --type=merge || true
+#           kubectl get applications.argoproj.io -n argocd -o name 2>/dev/null | \
+#             xargs -r -I {} kubectl patch {} -n argocd -p '{"metadata":{"finalizers":[]}}' --type=merge || true
+#           kubectl get ingress -A -o name 2>/dev/null | \
+#             xargs -r -I {} kubectl patch {} -p '{"metadata":{"finalizers":[]}}' --type=merge || true
+#           echo "🗑️ Deleting ingresses..."
+#           kubectl delete ingress --all -A --timeout=60s || true
+#           echo "🗑️ Deleting ArgoCD ApplicationSets..."
+#           kubectl delete applicationset.argoproj.io --all -n argocd --timeout=60s || true
+#           echo "🗑️ Deleting ArgoCD Applications..."
+#           kubectl delete applications.argoproj.io --all -n argocd --timeout=60s || true
+#           echo "🗑️ Uninstalling ArgoCD..."
+#           helm uninstall argocd -n argocd --timeout=2m || true
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.5.7
 
-      - name: Configure AWS
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
-          aws-region: ${{ env.AWS_REGION }}
-          role-session-name: github-actions
+#   destroy-bootstrap:
+#     needs: deploy
+#     if: github.event.inputs.action == 'destroy' && success()
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v4
 
-      - name: Terraform Init
-        run: |
-          cd infra
-          terraform init -upgrade
+#       - name: Setup Terraform
+#         uses: hashicorp/setup-terraform@v2
+#         with:
+#           terraform_version: 1.5.7
 
-      - name: Destroy Bootstrap Infra
-        run: |
-          cd infra
-          terraform destroy -auto-approve
+#       - name: Configure AWS
+#         uses: aws-actions/configure-aws-credentials@v4
+#         with:
+#           role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
+#           aws-region: ${{ env.AWS_REGION }}
+#           role-session-name: github-actions
+
+#       - name: Terraform Init
+#         run: |
+#           cd infra
+#           terraform init -upgrade
+
+#       - name: Destroy Bootstrap Infra
+#         run: |
+#           cd infra
+#           terraform destroy -auto-approve
