uncomment destroy

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -50,81 +50,81 @@ jobs:
           aws-region: ${{ env.AWS_REGION }}
           role-session-name: github-actions
 
-      # # Update kubeconfig
-      # - name: Update kubeconfig for EKS
-      #   if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
-      #   run: |
-      #     aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}
+      # Update kubeconfig
+      - name: Update kubeconfig for EKS
+        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
+        run: |
+          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}
 
-      # # Configure aws-auth
-      # - name: Configure aws-auth
-      #   if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
-      #   run: |
-      #     cat <<EOF | kubectl apply -f -
-      #     apiVersion: v1
-      #     kind: ConfigMap
-      #     metadata:
-      #       name: aws-auth
-      #       namespace: kube-system
-      #     data:
-      #       mapUsers: |
-      #         - userarn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:user/${{ secrets.AWS_USER }}
-      #           username: ${{ secrets.AWS_USER }}
-      #           groups:
-      #             - system:masters
-      #     EOF
+      # Configure aws-auth
+      - name: Configure aws-auth
+        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
+        run: |
+          cat <<EOF | kubectl apply -f -
+          apiVersion: v1
+          kind: ConfigMap
+          metadata:
+            name: aws-auth
+            namespace: kube-system
+          data:
+            mapUsers: |
+              - userarn: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:user/${{ secrets.AWS_USER }}
+                username: ${{ secrets.AWS_USER }}
+                groups:
+                  - system:masters
+          EOF
 
-      # # Install ArgoCD
-      # - name: Install ArgoCD
-      #   if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
-      #   run: |
-      #     helm repo add argo https://argoproj.github.io/argo-helm
-      #     helm repo update
-      #     helm upgrade --install argocd argo/argo-cd \
-      #       --namespace argocd \
-      #       --create-namespace \
-      #       --set server.service.type=LoadBalancer \
-      #       --set-string server.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"=classic \
-      #       --set server.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-name"="${{ env.ARGOCD_CLB }}"
-      #     kubectl -n argocd rollout status deployment/argocd-server --timeout=5m
+      # Install ArgoCD
+      - name: Install ArgoCD
+        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
+        run: |
+          helm repo add argo https://argoproj.github.io/argo-helm
+          helm repo update
+          helm upgrade --install argocd argo/argo-cd \
+            --namespace argocd \
+            --create-namespace \
+            --set server.service.type=LoadBalancer \
+            --set-string server.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"=classic \
+            --set server.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-name"="${{ env.ARGOCD_CLB }}"
+          kubectl -n argocd rollout status deployment/argocd-server --timeout=5m
 
-      # # Deploy apps
-      # - name: Get VPC and Deploy Apps
-      #   if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
-      #   run: |
-      #     export VPC_ID=$(aws ec2 describe-vpcs \
-      #       --filters "Name=tag:Name,Values=${{ env.VPC_NAME }}" \
-      #       --query "Vpcs[0].VpcId" --output text)
-      #     export ECR_NAME=${{ secrets.ECR_NAME }}
-      #     export AWS_ACCOUNT_NUMBER=${{ secrets.AWS_ACCOUNT_NUMBER }}
-      #     envsubst < ArgoCD/externalCharts/infra.yaml | kubectl apply -f -
-      #     envsubst < ArgoCD/myChart/argo.yaml | kubectl apply -f -
-      #     sleep 10
-      #     kubectl get applications -n argocd
+      # Deploy apps
+      - name: Get VPC and Deploy Apps
+        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
+        run: |
+          export VPC_ID=$(aws ec2 describe-vpcs \
+            --filters "Name=tag:Name,Values=${{ env.VPC_NAME }}" \
+            --query "Vpcs[0].VpcId" --output text)
+          export ECR_NAME=${{ secrets.ECR_NAME }}
+          export AWS_ACCOUNT_NUMBER=${{ secrets.AWS_ACCOUNT_NUMBER }}
+          envsubst < ArgoCD/externalCharts/infra.yaml | kubectl apply -f -
+          envsubst < ArgoCD/myChart/argo.yaml | kubectl apply -f -
+          sleep 10
+          kubectl get applications -n argocd
 
-      # # Smoke test
-      # - name: Smoke Test
-      #   if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
-      #   run: |
-      #     for i in {1..100}; do
-      #       http_status=$(curl -s -o /dev/null -w "%{http_code}" https://www.saharbittman.com || echo "000")
+      # Smoke test
+      - name: Smoke Test
+        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'workflow_run' }}
+        run: |
+          for i in {1..100}; do
+            http_status=$(curl -s -o /dev/null -w "%{http_code}" https://www.saharbittman.com || echo "000")
 
-      #       if [ "$http_status" = "200" ]; then
-      #         echo "✅ App is live! ($http_status)"
-      #         exit 0
-      #       fi
+            if [ "$http_status" = "200" ]; then
+              echo "✅ App is live! ($http_status)"
+              exit 0
+            fi
 
-      #       echo "⏳ Attempt $i/100 - Status: $http_status"
-      #       sleep 15
-      #     done
+            echo "⏳ Attempt $i/100 - Status: $http_status"
+            sleep 15
+          done
 
-      #     echo "❌ Smoke test failed"
-      #     exit 1
+          echo "❌ Smoke test failed"
+          exit 1
       
-      # # Trigger step (optional)
-      # - name: Push image to second AWS account
-      #   if: ${{ success() }}
-      #   run: echo "Image push to second account triggered."
+      # Trigger step (optional)
+      - name: Push image to second AWS account
+        if: ${{ success() }}
+        run: echo "Image push to second account triggered."
 
       # Login Docker to SOURCE ECR (first account)
       - name: Login to SOURCE ECR
@@ -157,8 +157,12 @@ jobs:
           docker tag "$SRC_ECR:$TAG" "$DST_ECR:$TAG"
           docker push "$DST_ECR:$TAG"
 
-
-
+      - name: Trigger DevOps_Prod repo
+        uses: peter-evans/repository-dispatch@v3
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          repository: sahar449/DevOps_Prod
+          event-type: trigger-from-bootstrap
 
        # ========== DESTROY ==========
       - name: Destroy Everything
